name: flutter_car_service
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  google_fonts: ^6.2.0
  flutter_svg:   # Specify version
  cached_network_image: ^3.2.0
  flutter_rating_bar: ^4.0.1
  animations: ^2.0.11
  url_launcher: ^6.3.0
  flutter_datetime_picker: ^1.5.1
  intl: ^0.19.0  # Specify version
  icons_plus: ^5.0.0
  flutter_emoji_feedback: ^0.4.0   # Specify version
  provider: ^6.0.0  # Specify version
  image_picker: ^1.1.2  # Specify version
  firebase_core: ^3.4.0
  firebase_auth: ^5.3.1  # Specify version
  cloud_firestore: ^5.4.0
  firebase_storage: ^12.2.0
  table_calendar: ^3.0.0
  shared_preferences:   # Specify version
  firebase_messaging: ^15.1.3  # Specify version
  flashy_tab_bar2: ^0.0.10
  swipeable_tile: ^2.0.1
  quickalert: ^1.0.0  # Specify version
  awesome_snackbar_content: ^0.1.4  # Specify version
  flutter_sliding_box:  # Specify version
  carousel_slider: ^5.0.0  # Specify version
  circle_nav_bar:  # Specify version
  custom_sliding_segmented_control: # Specify version
  cloud_functions: ^5.1.3
  local_auth: ^2.1.0  # Add this for biometric authentication
  flutter_secure_storage: ^6.0.0
  google_sign_in: ^6.2.1
  in_app_review:
  another_stepper: 
  
  

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/logo/
